name = "videoembedfix"
type = "javascript"
account_id = ""
compatibility_date = "2021-11-18"
workers_dev = true
kv_namespaces = [
  { binding = "VEF_CACHE", id = "" }
]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.development]
kv_namespaces = [
  { binding = "VEF_CACHE", id = "" }
]
